//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseRemove.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Household
    {
        public int Id { get; set; }
        public string HouseType { get; set; }
        public string HouseProperty { get; set; }
        public string CompensationType { get; set; }
        public System.DateTime RemoveTime { get; set; }
        public string Name { get; set; }
        public string CardNumber { get; set; }
        public string Mobile { get; set; }
        public string PubliclyOwned { get; set; }
        public string Successor { get; set; }
        public string BuildTime { get; set; }
        public string Address { get; set; }
        public string HouseUseFor { get; set; }
        public string UseStatus { get; set; }
        public string IsPartUse { get; set; }
        public string LandParcel { get; set; }
        public float Area { get; set; }
        public float UsefullArea { get; set; }
        public string PropertyRightNumber { get; set; }
        public string PropertyRightRemark { get; set; }
        public string LesseeNumber { get; set; }
        public decimal AssessPrice { get; set; }
        public decimal ZhuangxiuPrice { get; set; }
        public decimal BusinessCompensation { get; set; }
        public decimal YingFa { get; set; }
        public decimal ShiFa { get; set; }
        public string SignStatus { get; set; }
        public Nullable<System.DateTime> InspectTime { get; set; }
        public string InspectNumber { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int HRemoveId { get; set; }
        public string ComAreaRenge { get; set; }
    
        public virtual HRemove HRemove { get; set; }
        public virtual SignInfo SignInfo { get; set; }
        public virtual UnSignInfo UnSignInfo { get; set; }
    }
}
