//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseRemove.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnSignInfo
    {
        public int Id { get; set; }
        public string UnSignType { get; set; }
        public string UnSignRemark { get; set; }
        public Nullable<System.DateTime> YueTanTime { get; set; }
        public Nullable<System.DateTime> YueTan2Time { get; set; }
        public Nullable<System.DateTime> YueTan3Time { get; set; }
        public Nullable<System.DateTime> PingGuBaoGaoTime { get; set; }
        public Nullable<System.DateTime> PingGuBaoGaoSongDaTime { get; set; }
        public Nullable<System.DateTime> BaoSongFaGuiKeTime { get; set; }
        public Nullable<System.DateTime> TuiJuanTime { get; set; }
        public Nullable<System.DateTime> ZaiCiSongBaoTime { get; set; }
        public Nullable<System.DateTime> DanHuBuChangXiaDaTime { get; set; }
        public Nullable<System.DateTime> DanHuBuChangSongDaTime { get; set; }
        public Nullable<System.DateTime> QiSuQiDaoQiTime { get; set; }
        public Nullable<System.DateTime> CuiGaoShuSongDaTime { get; set; }
        public Nullable<System.DateTime> QiangZhiZhiXingTiBaoFaGuiKeTime { get; set; }
        public Nullable<System.DateTime> FaYuanLiAnTime { get; set; }
        public Nullable<System.DateTime> XiaDaZhuiYuZhiXingCaiDingTime { get; set; }
        public Nullable<System.DateTime> CheHuiTime { get; set; }
        public string CheHuiYuanYin { get; set; }
    
        public virtual Household Household { get; set; }
    }
}
